version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: f1_postgres
    environment:
      POSTGRES_DB: f1miniatures
      POSTGRES_USER: f1user
      POSTGRES_PASSWORD: f1password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U f1user -d f1miniatures"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - f1_network

  # Aplicação Flask
  app:
    build: .
    container_name: f1_app
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://f1user:f1password@db:5432/f1miniatures
      FLASK_ENV: development
      FLASK_DEBUG: "True"
    volumes:
      - .:/app  # Para desenvolvimento (hot reload)
      - uploads_data:/app/static/uploads  # Persistir fotos
    networks:
      - f1_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  f1_network:
    driver: bridge